#!/bin/sh
# This is a POSIX compliant script so it works with both bash AND sh on more distributions

arch=$(uname -m)
case "$arch" in
    x86_64*)
        echo "Found x64 Architecture - Publishing for that..."
        dotnet publish -r linux-x64 --self-contained true --property:PublishDir=bin/linux-x64/,assemblyname=reecon,PublishSingleFile=True,EnableCompressionInSingleFile=true,PublishTrimmed=true --configuration=Release
        ;;
    aarch64)
        echo "Found ARM64 Architecture - Publishing for that..."
        dotnet publish -r linux-arm64 --self-contained true --property:PublishDir=bin/linux-arm64/,assemblyname=reecon,PublishSingleFile=True,EnableCompressionInSingleFile=true,PublishTrimmed=true --configuration=Release
        ;;
    *)
        echo "Unknown CPU Architecture - Bug Reelix!"
        ;;
esac